version: '3.8'

networks:
  customer-network:
    name: customer-network

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/node/app
      - node-modules-vol:/home/node/app/node_modules
    networks:
      - customer-network
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DB: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: postgres

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - customer-network

volumes:
  postgres-data:
  pgadmin-data:
  node-modules-vol:
